#!/bin/sh

fastboot flash partition gpt_sd_both0.bin
fastboot flash hyp hyp.mbn
fastboot flash rpm rpm.mbn
fastboot flash sbl1 sbl1.mbn
fastboot flash tz tz.mbn
fastboot flash sec sec.dat
fastboot flash aboot emmc_appsboot.mbn

fastboot erase boot
fastboot erase system-boot
fastboot erase writable

fastboot flash boot emmc-sd_u-boot.img
fastboot flash system-boot system-boot.img
fastboot flash writable writable.img
